# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Build ASP.NET Core project using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core?view=vsts
name: $(BuildDefinitionName).$(Major).$(Minor).Patch.$(Rev:.r)
pool:
  vmImage: 'Ubuntu 16.04'
  
variables:
  buildConfiguration: 'Release'
  Major: '1'
  Minor: '0'
  Patch: '0'

steps:

- script: |
    dotnet build --configuration $(buildConfiguration)
    dotnet publish --configuration $(buildConfiguration) --output $BUILD_ARTIFACTSTAGINGDIRECTORY

- task: PublishBuildArtifacts@1
  displayName: 'publish build artifacts'

- task: DotNetCoreCLI@2
  displayName: 'pack nuget package'
  inputs:
    command: 'pack'
    configuration: 'release'
    packagesToPack: '**/*.csproj' # Required when command == pack
    packDirectory: '$(build.artifactStagingDirectory)' # Optional
    nobuild: false # Optional
    versioningScheme: 'byPrereleaseNumber' # Options: off, byPrereleaseNumber, byEnvVar, byBuildNumber
    #versionEnvVar: $(ver)# Required when versioningScheme == byEnvVar
    majorVersion: '$(Major)' # Required when versioningScheme == byPrereleaseNumber
    minorVersion: '$(Minor)' # Required when versioningScheme == byPrereleaseNumber
    patchVersion: '$(Patch)' # Required when versioningScheme == byPrereleaseNumber
    #buildProperties: # Optional
    verbosityPack: 'detailed' # Options: quiet, minimal, normal, detailed, diagnostic

# .NET Core
# Push NuGet packages.
- task: DotNetCoreCLI@2
  displayName: 'publish nuget artifact'
  inputs:
    command: 'push'
    nuGetFeedType: 'internal' # Required when command == push. Options: internal, external
    packagesToPush: '$(build.artifactStagingDirectory)/*.nupkg' # Required when command == push
    publishVstsFeed: 'https://redpulsetek.pkgs.visualstudio.com/_packaging/L2RPacketLogger@Prerelease/nuget/v3/index.json' # Required when command == push && NuGetFeedType == internal
    #publishFeedCredentials: # Required when command == push && NuGetFeedType == external
